
CREATE DATABASE ventaentradas;
USE ventaentradas;

CREATE TABLE USUARIOS (
CORREO_ELECTRONICO VARCHAR(50) NOT NULL,
PASSWD VARCHAR(64) NOT NULL,
FECHA_ALTA DATE,
EDAD INT(3),
APELLIDOS VARCHAR(50) NOT NULL,
NOMBRE VARCHAR(50) NOT NULL,
TIPO_USUARIO TINYINT(1),
PRIMARY KEY (CORREO_ELECTRONICO)
);

CREATE TABLE LUGAR(
ID_LUGAR INT(5) NOT NULL AUTO_INCREMENT,
LOCALIDAD VARCHAR(50) NOT NULL,
PROVINCIA VARCHAR(50),
PAIS VARCHAR(50),
LATITUD FLOAT(3,2),
LONGITUD FLOAT(3,2),
PRIMARY KEY (ID_LUGAR)
);

CREATE TABLE EVENTOS (
ID_EVENTO INT(5) NOT NULL AUTO_INCREMENT,
NOMBRE VARCHAR(50) NOT NULL,
TIPO VARCHAR(50),
PRECIO FLOAT(3,2) NOT NULL,
URL VARCHAR(255),
FECHA_INICIO DATE NULL,
FECHA_FIN DATE,
ID_LUGAR INT(5) NOT NULL,
PRIMARY KEY (ID_EVENTO),
FOREIGN KEY fk1 (ID_LUGAR) REFERENCES LUGAR(ID_LUGAR)
);


CREATE TABLE COMPRA(
NUMERO_ENTRADAS INT(3) NOT NULL,
CORREO_ELECTRONICO VARCHAR(50) NOT NULL,
ID_EVENTO INT(5) NOT NULL,
PRIMARY KEY (CORREO_ELECTRONICO, ID_EVENTO),
FOREIGN KEY (CORREO_ELECTRONICO) REFERENCES USUARIOS(CORREO_ELECTRONICO),
FOREIGN KEY (ID_EVENTO) REFERENCES EVENTOS(ID_EVENTO)
);

CREATE TABLE ARTISTA(
ID_ARTISTA INT(5) NOT NULL AUTO_INCREMENT,
NOMBRE VARCHAR(50) NOT NULL,
GENERO VARCHAR(50),
DESCRIPCION VARCHAR(60000),
IMAGEN VARCHAR(100),
URL VARCHAR(100),
PRIMARY KEY (ID_ARTISTA)
);

CREATE TABLE ASISTE (
ID_EVENTO INT(5) NOT NULL,
ID_ARTISTA INT(5) NOT NULL,
PRIMARY KEY (ID_EVENTO, ID_ARTISTA),
FOREIGN KEY (ID_ARTISTA) REFERENCES ARTISTA(ID_ARTISTA),
FOREIGN KEY (ID_EVENTO) REFERENCES EVENTOS(ID_EVENTO)
);
